### ISSUE TITLE
/lockout and /blackout commands aren't working

### ISSUE THREAD

**Issue by Hephaestus-11** [marin774/lockout-fabric#15]
So, when I try to run the /lockout or /blackout commands, it just shows the incomplete red command thing when a command doesnt work. Howver, other commands associated with the mod do work, like /BoardBuilder. Any idea how to fix this?

**Comment by marin774** [comment]
if you are using a dedicated server, check out #3 (also make sure you have admin/op permissions)
if you are creating a singleplayer world, turn cheats ON (or open to LAN and turn them on)

**Comment by Hephaestus-11** [comment]
It's on a singleplayer world hosted by Lunar Client, which does allow mods. It's on the right version, and like I said, BoardBuilder and other such commands do work, but not /lockout or /blackout. I don't know if the Lunar Client thing is interfering with it, but I would guess that that's the case, so I'll try to host on LAN by just using the Fabric launcher instead of Lunar.

**Comment by marin774** [comment]
It should definitely work on Lunar, as long as cheats are enabled in the singleplayer world. Some other commands are client-sided and don't require any permission.
