### ISSUE TITLE
/lockout & /blackout commands not appearing on a server

### ISSUE THREAD

**Issue by wclxb** [marin774/lockout-fabric#3]
I'm self hosting a Minecraft fabric server. I've put the lockout mod along with the fabric api in the mods folder, and the lockout and blackout commands don't show up as valid. I tested version 0.6 and 0.5. In version 0.6, the CustomBoard and LoadCustomBoard commands are there, but the lockout and blackout commands aren't.

The version of Minecraft is 1.20.1, and with the same mod setup on the client, the lockout and blackout commands show up in a single player world just fine.

**Comment by marin774** [comment]
Solved, launch the server with startup scripts (run.bat/start.bat) instead of double-clicking the server jar 😅
